### ISSUE TITLE
Tagasiside ja idee/küsimus

### ISSUE THREAD

**Issue by collectorofbones** [open-eid/hwcrypto.js#12]
1. Kas on ka mingi kiirem kanal suhtluseks kui issue-tracker? Praeguste küsimuste ja teemade juures tundub see pisut ebasobiv või aeglane. samas sk suunas siia.

2. sai just (15.aprill) chrome 42 installeeritud, ja https://open-eid.github.io/hwcrypto.js/sign.html ei tööta. Autodetect ei suuda sobivat backendi laadida. Kas see ajutine probleem (viimasest commitist mõnda aega juba möödas) või peaks siiski kõik töötama? (vähe vanema js failiga (see kus versiooni number on 0.1.0) chrome 41 veel toimis)

3. ja peamine teema: praegune hwcrypto lahendus on üles ehitatud ideele, et leht laaditakse ühe korra, ning sisu muudatused (peale serdi laadimist allkirjastamine) laetakse taustal ajaxi päringutega. Samas vana lahendus (idCard.js) oli oma olemuselt uus post/uus leht iga sammu järel. Sellest tulenevalt ongi nüüd raske dilemma - kas hakata
 a) äriloogikat ümber kirjutama (mis on küll tehtav ja ilmselt pikas perspektiivis õigem toetamaks parmeini hwcrypto tulevasi versioone) või 
 b) muuta hwcrypto.js selliselt et see toetaks erinevaid lehti. Praegu olen selle teise variandi peal, ja mida ma tegin:

108a109,112
>         // by BC
>         this.set_certificate_id = function(cert, id){
>             certificate_ids[cert] = id;
>         };
119a124
>                         // ",\nid: v.id" by BC
121c126,127
<                             hex: v.cert
---
>                             hex: v.cert,
>                             id: v.id
276a283,293
>     };
>     // by BC
>     fields.set_certificate_id = function(cert, id){
>         if(_backend == null) {
>             console.log("backend is null, use _autodetect");
>             _autodetect().then(function(result){
>                 _backend.set_certificate_id(cert, id);
>             });
>         }else{
>             _backend.set_certificate_id(cert, id);
>         }

ehk laadimisel võtan ka serdi id, panen selle lehe post parameetritesse ning hiljem initsialiseerin backendi uuesti ning lisan sertifikaadi. Vastik häkk, aga ühilduvuse seisukohast on see vähem koodi muudatust kui hakata praeguseid POST lehekülgi ümber kirjutama. Mis on arvamus? Samas kui see patch saaks peale panna ka reposse, siis lahendaks see ehk ka teistel analoogse probleemi.

**Comment by martinpaljak** [comment]
1. martin.paljak@ria.ee, nagu wiki esilehel kirjas.
2. kui on paigaldatud peale Chrome uuendamist ka ID-kaardi tarkvara, siis peaks küll töötama (ka eelnevalt olemas olnud versioon töötab).
3. aasta on 2015, asünkroonsus ja "ühe-lehe-veebid" on norm. Keegi ei keela enda kasutuses olevat veebilehte ehitama nii nagu parasjagu tuju on (kolm POST päringut või 7) aga suuna näitajana ja toetatud API kasutuse osas ei ole mõtet tagurlust toetada. Juhin tähelepanu, et selle häki töötamine ei ole garanteeritud klienditarkvara uuenedes. Kui tahta "lihtsalt ja laisalt" teha siis on variant kaks korda küsida srtifikaati kasutaja käest.

**Comment by martinpaljak** [comment]
Aga FAQ jaoks on see mõistlik punkt. Kahe lehe vahel liikudes ei ole põhimõtteliselt võimalik tagada kasutaja poolt valitud sertifikaadi kasutamist kontekstis, mida kasutaja "luba andes" eeldas. Praegu ei tehta rangeid kontrolle olemasolevate pluginte poolt selle tagamiseks, aga kui see kunagi realiseeritakse (pigem varem kui hiljem) siis ei tööta analoogne parameetri kaasa panemine. Seega on mõistlik üle vaadata allkirjastamise realiseerimine pigem varem kui hiljem.

**Comment by collectorofbones** [comment]
Tänud!
Punkt 2 sai lahendatud, ning kolmanda osas täitsa nõus - pikas plaanis on igaljuhul mõistlikum ajaxi lahendus, lihtsalt esimese hooga tundus loogika muutus üllatav ning momendil paistab see "väike häkk" kiirem lahendus olema
