### ISSUE TITLE
IE9 fails if developer console is not opened

### ISSUE THREAD

**Issue by okhofstad** [open-eid/hwcrypto.js#14]
We are using hwcrypto 0.0.9 and hwcrypto-legacy 0.0.9.

When using IE9 to for signing, it all works great if the developer console (F12) is open. However, if a signing session is started without the console being open, the signing fails with the error "Unable to get value of the property 'getCertificate': object is null or undefined".

A similar issue can be observed at the test site https://open-eid.github.io/hwcrypto.js/sign.html, where the property 'use' is null or undefined.

Is this a know issue?

**Comment by martinpaljak** [comment]
Wow, this sounds like a nice thing to debug :)

No, this is not a known issue, it has been tested with older IE-s only via the compatibility mode.

If you open the console AFTER the signing fails, does IE9 show any past messages ?

**Comment by okhofstad** [comment]
If I open the console after the signing fails, no log messages are displayed.

However, if I first call getCertificate without having the console open, then open the console, and then call getCertificate once more you can see the new messages.

**Comment by martinpaljak** [comment]
Okay, turns out that IE8/9 only define console.* when devtools is open. Yet another reason to remove them from released code, available in a few minutes.
