### ISSUE TITLE
What about batch signatures?

### ISSUE THREAD

**Issue by jeesus** [open-eid/hwcrypto.js#19]
Hey

What about skipping the PIN2 input in case of batch signing multiple documents? In case user has to sign 100 documents, It would be convenient to not enter PIN2 for every single document. Is there any way to skip it?

**Comment by martinpaljak** [comment]
From API perspective, there is no PIN in question - it is the implementation detail of the backend, like chrome-token-signing or some other plugin. Moreover, the decision to cache a PIN (which is not acceptable for a legally binding signature anyway) is not done by the backend, but the card. If one uses a pinpad reader (the host has no knowledge of the PIN) the caching scenario would be impossible anyway.

So in the context of hwcrypto.js, this is not a question. And in the contxt of backends, not possible universally.
